### ISSUE TITLE
Issue w/ new version

### ISSUE THREAD

**Issue by WantToMakeNps** [Unovamata/AutoBuyerPlus#3]
![image](https://github.com/Unovamata/AutoBuyerPlus/assets/169542232/c9c4a5a2-982d-4a1c-84ee-a6c6231cd41f)

I'm getting thiswhen I removed the old autobuyer.

files unzipped were in download.
Developer mode I clicked load unpacked
![image](https://github.com/Unovamata/AutoBuyerPlus/assets/169542232/9bdc7392-de79-488c-9b3f-63aa2f0ec7f5)

![image](https://github.com/Unovamata/AutoBuyerPlus/assets/169542232/7bdb2f89-264a-49a4-9ca7-25f7ffa4ec89)

Not sure what caused the issue ^^|

**Comment by Unovamata** [comment]
Interesting, have you tried uninstalling and installing again the extension? AutoBuyer+ seems to get stuck in the Warning pop-up. Without accepting it you can't continue, so that is what is happening. Sorry for the inconvenience.

If you can confirm me the question I asked above I can push a hotfix in the following days! Thank you for your support!

**Comment by WantToMakeNps** [comment]
have you tried uninstalling and installing again the extension
----------------
Hi.
I tried this but it seems it did not work.

I didn't really getteh warning pop up.
Opens to a blue blank tab as present in the img above.



Thanks for taking a look at the issue! :)

**Comment by Unovamata** [comment]
Interesting!

Have you tried using another browser?
Have you reloaded the extension manually?

I imagine this is a fresh install because of the warning page. I did pushed a potential fix for the Warning screen so I'm puzzled about this situation.

The extension loads correctly in my testing environments so this may be an issue with your browser but I will like to know more about this issue to help you further.

Sorry about the inconvenience. 🙇‍♂️

[Can you give a read to FAQ #3 about error reporting?](https://github.com/Unovamata/AutoBuyerPlus/wiki/FAQs)

It may give me more information about what is happening. 

![AutoBuyerPlus](https://github.com/Unovamata/AutoBuyerPlus/assets/91705840/e89377dd-5d1d-4f82-97e4-95f97501af9e)

**Comment by Unovamata** [comment]
I will close this issue as no other advances have occurred.
